apiVersion: v1
kind: Pod
metadata:
  name: pir-audio-rpi1
spec:
  containers:
  - name: pir-audio-rpi1
    image: little170/rpi-mic-mqtt-panel:17000-v4
    securityContext:
      privileged: true
    command: ["/bin/bash","-c","python audio_record.py"]
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
    env:
    - name: BROKER
      value: "192.168.0.99"
    - name: TOPIC
      value: "audio"
  restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi1
