apiVersion: v1
kind: Pod
metadata:
  name: yolo-worker0
spec:
  containers:
  - name: yolo-worker0
    image: little170/yolo:pc-worker 
    command: ["python"]
    args: ["worker.py","--ps_hosts=140.114.79.60:8887","--worker_hosts=140.114.79.60:8888,140.114.79.67:8888","--job_name=worker","--task_index=0"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
    ports:
    - containerPort: 8888
      hostPort: 8888
  restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: minion1
