apiVersion: v1
kind: Pod
metadata:
  name: yolo
spec:
  containers:
  - name: yolo
    image: little170/yolo:pc-master
    command: ["python3"]
    args: ["yolo.py","images/cat.jpg"]
    env:
    - name: BROKER
      value: '140.114.79.61'
    - name: PERIOD 
      value: '5'
    - name: OP0 
      value: '0'
    - name: OP1 
      value: '1'
    - name: MASTER_PORT 
      value: '8887'
    - name: MASTER_IP 
      value: '140.114.79.60'
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: minion1
