apiVersion: v1
kind: Pod
metadata:
  name: pir-sensors-rpi1
spec:
  containers:
  - name: pir-sensors-rpi1
    image: little170/scalebox:pir-env-deviceid-v2
    command : ["bash","run.sh"]
    env:
    - name: DEVICE_ID 
      value: 'rpi1'
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi1

---

apiVersion: v1
kind: Pod
metadata:
  name: pir-sensors-rpi2
spec:
  containers:
  - name: pir-sensors-rpi2
    image: little170/scalebox:pir-env-deviceid-v2
    command : ["bash","run.sh"]
    env:
    - name: DEVICE_ID 
      value: 'rpi2'
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi2

---

apiVersion: v1
kind: Pod
metadata:
  name: pir-sensors-rpi3
spec:
  containers:
  - name: pir-sensors-rpi3
    image: little170/scalebox:pir-env-deviceid-v2
    command : ["bash","run.sh"]
    env:
    - name: DEVICE_ID 
      value: 'rpi3'
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi3
