apiVersion: v1
kind: Pod
metadata:
  name: get-image-rpi3
spec:
  containers:
  - name: get-image-rpi3
    image: little170/rpi-camera-mqtt:v2 
    command: ["/bin/bash","-c","python image-mqtt.py"]
    env:
    - name: TOPIC
      value: "image"
    - name: BROKER
      value: "192.168.0.99"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi3
