apiVersion: v1
kind: Pod
metadata:
  name: pir-tf-audio-rpi2
spec:
  containers:
  - name: pir-tf-audio-rpi2
    image: wakeup706/tensorflow-audio:rpi-subAudio-pubResult-info
    securityContext:
      privileged: true
    command: ["/bin/bash","-c","sh run.sh"]
    env:
    - name: BROKER
      value: "192.168.0.99"
  restartPolicy: Never
  nodeSelector:
    device: rpi2