apiVersion: v1
kind: Pod
metadata:
  name: heat-map 
spec:
  containers:
  - name: heat-map
    image: little170/heat-map-mqtt:master 
    command: ["/bin/bash","-c","python heat_map_pub.py"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  #restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: master 
