apiVersion: v1
kind: Pod
metadata:
  name: yolo-rpi3
spec:
  containers:
  - name: yolo-rpi3
    image: wakeup706/tensorflow-yolo:rpi-subIamge-analyze-pubResultImage 
    command: ["/bin/bash","run.sh"]
    env:
    - name: PUB_TOPIC
      value: "iot-1/d/0242ac110302/evt/image/jason"
    - name: TOPIC
      value: "image"
    - name: BROKER
      value: "192.168.0.99"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/mem
      name: mem
  restartPolicy: Never
  volumes:
  - name: mem
    hostPath:
      path: /dev/mem
  nodeSelector:
    device: rpi3
